// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZadaniaApi.Data;

#nullable disable

namespace ZadaniaApi.Migrations
{
    [DbContext(typeof(BazaDbContext))]
    [Migration("20260202105000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("RestAPI_zadania.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rola")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("RestAPI_zadania.Models.Zadanie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CzyWykonane")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdUzytkownik")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdUzytkownik");

                    b.ToTable("Zadania");
                });

            modelBuilder.Entity("RestAPI_zadania.Models.Zadanie", b =>
                {
                    b.HasOne("RestAPI_zadania.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("Zadania")
                        .HasForeignKey("IdUzytkownik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("RestAPI_zadania.Models.Uzytkownik", b =>
                {
                    b.Navigation("Zadania");
                });
#pragma warning restore 612, 618
        }
    }
}
